DEFINES+=PROJECT_CONF_H=\"project-conf.h\"
CONTIKI_PROJECT = udp-root
#APPS += powertrace
all: $(CONTIKI_PROJECT)


NETSTACK_CONF_WITH_IPV6 = 1
CONTIKI_WITH_IPV6 = 1

CONTIKI = ../..
include $(CONTIKI)/Makefile.include
