#!/bin/bash

# Usage
if [ $# -eq 3 ]; then
  START=$1
  END=$2
  TEST=$3
else
  echo "Usage: $0 <nr_start> <nr_end> <test>"
  echo "Example: $0 1 10 cooja_helloworld"
  exit 1
fi

# Locate Contiki/COOJA
if [ -z "$CONTIKI" ]; then
  if [ -z "$CONTIKI_HOME" ]; then
  	CONTIKI_HOME=../../..
  fi
  CONTIKI=$CONTIKI_HOME
fi

# Clean up
#rm -f *.log *.cooja_log
rm -f *.cooja_log
rm -fr se obj_cooja
rm -f symbols.c symbols.h

# Compile COOJA
echo ">>>>>>> Building COOJA <<<<<<<<"
(cd $CONTIKI/tools/cooja && ant clean && ant jar)
if [ "$?" != "0" ]; then
  echo "Compilation of COOJA failed"
  exit 1
fi

REPEATS='$END-$START+1'

# Run tests
for COUNTER in `seq $START $END`;
do
  echo $COUNTER
  echo ">>>>>>> Test $COUNTER/$REPEATS: $TEST-$COUNTER.log <<<<<<<<"
  bash RUN_TEST $TEST RUN_REPEATED_LAST.log
  mv $TEST.log $TEST-$COUNTER.log
done

echo
cat RUN_REPEATED_LAST.log
echo
echo ">>>>>>> DONE! Test logs stored in $TEST-[1-$REPEATS].log <<<<<<<<"
